config/routes.rb
Lurch::Application.routes.draw do
  resources :github,  :only => :create
  resources :jenkins, :only => :create
  resources :settings
  resources :projects do
    resources :builds
  end
  resources :builds

  root :to => 'projects#index'
end

app/models/setting.rb
class Setting < ActiveRecord::Base
  attr_accessible :key, :value

  def self.by_key(key)
    Setting.find_by_key(key).try(:value)
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  # GET /settings
  # GET /settings.json
  def index
    @settings = Setting.all
  end

  # GET /settings/1
  # GET /settings/1.json
  def show
    @setting = Setting.find(params[:id])
  end

  # GET /settings/new
  # GET /settings/new.json
  def new
    @setting = Setting.new
  end

  # GET /settings/1/edit
  def edit
    @setting = Setting.find(params[:id])
  end

  # POST /settings
  # POST /settings.json
  def create
    @setting = Setting.new(params[:setting])

    if @setting.save
      redirect_to(@setting, :notice => 'Setting was successfully created.')
    else
      render(:action => 'new')
    end
  end

  # PUT /settings/1
  # PUT /settings/1.json
  def update
    @setting = Setting.find(params[:id])

    if @setting.update_attributes(params[:setting])
      redirect_to(@setting, :notice => 'Setting was successfully updated.')
    else
      render(:action => 'edit')
    end
  end

  # DELETE /settings/1
  # DELETE /settings/1.json
  def destroy
    @setting = Setting.find(params[:id])
    @setting.destroy

    redirect_to(settings_url)
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_form.html.haml
= form_for @setting do |f|
  - if @setting.errors.any?
    #error_explanation
      %h2= "#{pluralize(@setting.errors.count, "error")} prohibited this setting from being saved:"
      %ul
        - @setting.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :key
    = f.text_field :key
  .field
    = f.label :value
    = f.text_field :value
  .actions
    = f.submit 'Save'

app/views/settings/edit.html.haml
%h1 Editing setting

= render 'form'

= link_to 'Show', @setting
\|
= link_to 'Back', settings_path

app/views/settings/index.html.haml
%h1 Settings

%table.table.condensed.table-striped
  - @settings.each do |setting|
    %tr
      %td= setting.key
      %td= setting.value
      %td= link_to '<i class="icon-edit"></i>'.html_safe, edit_setting_path(setting)
      %td= link_to '<i class="icon-remove"></i>'.html_safe, setting, method: :delete, data: { confirm: 'Are you sure?' }

app/views/settings/new.html.haml
%h1 New setting

= render 'form'

= link_to 'Back', settings_path

app/views/settings/show.html.haml
%p#notice= notice

%p
  %b Key:
  = @setting.key
%p
  %b Value:
  = @setting.value

= link_to 'Edit', edit_setting_path(@setting)
\|
= link_to 'Back', settings_path