config/routes.rb
Lurch::Application.routes.draw do
  resources :github,  :only => :create
  resources :jenkins, :only => :create
  resources :settings
  resources :projects do
    resources :builds
  end
  resources :builds

  root :to => 'projects#index'
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :jenkins_id, :repo

  validates :repo, :presence => true
  validates :jenkins_id, :presence => true, :uniqueness => true

  has_many :builds, :dependent => :destroy

  def to_param
    jenkins_id
  end

  def last_build
    builds.order('created_at DESC').first
  end

  def jenkins_url
     base = Setting.by_key('jenkins_url').to_s.chomp('/')
     base = "http://#{base}" unless base =~ /https?:\/\//

    "#{base}/job/#{jenkins_id}"
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.order("updated_at desc")
  end

  def show
    @project = Project.find_by_jenkins_id(params[:id])
  end

  def new
    @project = Project.new
  end

  def edit
    @project = Project.find_by_jenkins_id(params[:id])
  end

  def create
    @project = Project.new(params[:project])

    begin
      ProjectCreator.new(@project).create!
    rescue
      render(:action => "new") and return
    end

    redirect_to(@project, :notice =>'Project was successfully created.')
  end

  def update
    @project = Project.find_by_jenkins_id(params[:id])

    begin
      ProjectCreator.new(@project).update_attributes!(params[:project])
    rescue
      render action: "edit" and return
    end

    redirect_to(@project, :notice => 'Project was successfully updated.')
  end

  def destroy
    @project = Project.find_by_jenkins_id(params[:id])
    @project.destroy

    redirect_to(projects_url)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= form_for @project do |f|
  - if @project.errors.any?
    #error_explanation
      %h2= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :repo, "Repository (i.e. br/breport)"
    = f.text_field :repo
  .field
    = f.label :jenkins_id, "Jenkins Identifier (optional)"
    = f.text_field :jenkins_id
  .actions
    = f.submit 'Save'

app/views/projects/edit.html.haml
%h1 Editing project

= render 'form'

= link_to 'Show', @project
\|
= link_to 'Back', projects_path

app/views/projects/index.html.haml
%table.table.condensed
  - @projects.each do |project|
    %tr{:class => build_bootstrap_class(project.last_build)}
      %td
        - if project.last_build.try(:succeeded?)
          %i.icon-ok-sign
        - elsif project.last_build.try(:failed?)
          %i.icon-remove-sign
        - else
          %i.icon-time

        = project.jenkins_id
      %td= link_to(project.repo, "https://github.com/#{project.repo}")
      %td
        - if project.last_build
          = link_to(project.last_build.ref, project.last_build.ref_url)
      %td= link_to("View on Jenkins", project.jenkins_url)
      %td= link_to("Builds", project_builds_url(project))
      %td
        - if project.last_build
          %small= link_to(project.last_build.created_at.strftime('%m/%d/%Y %I:%M %p'), project.last_build)
      %td= link_to '<i class="icon-repeat"></i>'.html_safe, project_builds_path(project), :method => :post
      %td= link_to '<i class="icon-edit"></i>'.html_safe, edit_project_path(project)
      %td= link_to '<i class="icon-remove"></i>'.html_safe, project, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Project', new_project_path

app/views/projects/new.html.haml
%h1 New project

= render 'form'

= link_to 'Back', projects_path

app/views/projects/show.html.haml
%p#notice= notice

%p
  %b Repo:
  = @project.repo
%p
  %b Jenkins:
  = link_to("View project in Jenkins", @project.jenkins_url)

= link_to 'Builds', project_builds_path(@project)
\|
= link_to 'Edit', edit_project_path(@project)
\|
= link_to 'Back', projects_path